
esphome:
  name: insegna-o

esp8266:
  board: d1

logger:

api:
  password: ""

ota:
  password: ""
  platform: esphome

wifi:
  ssid: "SoffittaAXSlow"
  password: !secret wifi_pw_soffitta

  manual_ip:
    static_ip: 192.168.1.93
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# RGB component
light:
  - platform: rgb
    name: "Insegna O"
    red: output_red
    green: output_green
    blue: output_blue

# RGB pins
output:
  - platform: esp8266_pwm
    inverted: true
    id: output_red
    pin: D9
  - platform: esp8266_pwm
    inverted: true
    id: output_green
    pin: D8
  - platform: esp8266_pwm
    inverted: true
    id: output_blue
    pin: D10

binary_sensor:
  # Open main door button
  - platform: gpio
    id: redButton
    internal: true
    on_press:
      - homeassistant.service:
          service: button.press
          data:
            entity_id: button.apri_portone
    filters:
      - delayed_on: 20ms
      - delayed_off: 20ms
    pin:
      number: D11
      inverted: true
      mode:
        input: true
        pullup: true
  # Home door opening sensors
  - platform: gpio
    id: frontDoorOpen
    name: Front Door
    pin:
      number: D3
      inverted: true
      mode:
        input: true
        pullup: true      

