
esphome:
  name: portone-control

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""
  platform: esphome

wifi:
  ssid: "Quarto"
  password: !secret wifi_pw_quarto

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.92
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
  
button:
  - platform: template
    name: Apri Portone
    id: pulsantePortone
    on_press:
      - switch.turn_on: relayPortone

switch:
  - platform: gpio
    pin: GPIO0
    inverted: true
    internal: true
    id: relayPortone
    name: "Portone Relay"
    on_turn_on:
    - delay: 1500ms
    - switch.turn_off: relayPortone