
esphome:
  name: portone-control

esp8266:
  board: esp01_1m

logger:

api:
  password: ""

ota:
  password: ""
  platform: esphome

wifi:
  ssid: !secret wifi_name_quarto
  password: !secret wifi_pw_quarto

# Relay board control
button:
  - platform: template
    name: Apri Portone
    id: pulsantePortone
    on_press:
      - switch.turn_on: relayPortone

switch:
  - platform: gpio
    pin: GPIO0
    inverted: true
    internal: true
    id: relayPortone
    name: "Portone Relay"
    on_turn_on:
    - delay: 1500ms
    - switch.turn_off: relayPortone