esphome:
  name: power-display-ring

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "SoffittaAXSlow"
  password: "BelinoInverso"

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.94
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

sensor:
  - platform: homeassistant
    id: p_tot_color
    entity_id: sensor.power_tot
    internal: true
    filters:
      - calibrate_linear:
          # Map 100.0 (from sensor) to 255.0 (true value)
          - 0.0 -> 0.0
          - 3900.0 -> 255.0
  
  - platform: homeassistant
    id: p_tot_number_on
    entity_id: sensor.power_tot
    internal: true
    filters:
      - calibrate_linear:
          # Map 100.0 (from sensor) to 8.0 (true value)
          - 0.0 -> 0.0
          - 3900.0 -> 12.0

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: D3
    num_leds: 12
    id: ring_leds
    internal: True
    effects:
      - addressable_lambda:
          update_interval: 50ms
          lambda: |-
            for (int j = 0; j < 12; j++) {
              if (id(p_tot_number_on).state > j) {
                it[j] = ESPColor(256.0-(id(p_tot_color).state), id(p_tot_color).state, 0);
              } else {
                it[j] = ESPColor(0, 0, 0);
              }
            }