esphome:
  name: power-display-ring

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "SoffittaAXSlow"
  password: "BelinoInverso"

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.94
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

sensor:
  - platform: homeassistant
    id: p_tot_color
    entity_id: sensor.power_tot
    internal: true
    filters:
      - calibrate_linear:
          # Map 3900.0 (from sensor) to 255.0 (true value)
          - 0.0 -> 0.0
          - 3900.0 -> 255.0 # 3900W is the max power output before forced disconnection
  
  - platform: homeassistant
    id: p_tot_number_on
    entity_id: sensor.power_tot
    internal: true
    filters:
      - calibrate_linear:
          # Map 3900.0 (from sensor) to 8.0 (true value)
          - 0.0 -> 0.0
          - 3900.0 -> 12.0

light:
  - platform: neopixelbus
    type: GRB
    pin: GPIO3
    num_leds: 12
    variant: WS2812
    method:
      type: esp8266_dma    
    internal: True
    id: led_ring
    name: "LEDRing"
    restore_mode: ALWAYS_ON
    effects: 
      - addressable_lambda:
          name: "Power level"
          update_interval: 50ms
          lambda: |-
            for (int i = 0; i < it.size(); i++) {
              if (id(p_tot_number_on).state > i) {
                it[i] = Color(255.0 - (id(p_tot_color).state), id(p_tot_color).state, 0);
              } else {
                it[i] = Color(0, 0, 0);
              }
            }
    on_turn_on:
      - light.turn_on: 
          id: led_ring
          effect: "Power level"