esphome:
  name: speaker_a
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_name_soffitta
  password: !secret wifi_pw_soffitta
  power_save_mode: none

captive_portal:

logger:

api:
  password: ""

ota:
  password: ""
  platform: esphome

output:
  - platform: gpio
    pin: GPIO27
    id: PAM8302_mute

i2s_audio:
  i2s_lrclk_pin: GPIO14  # WS/LRCK pin
  i2s_bclk_pin: GPIO13   # Bit Clock pin

# Media Player setup
media_player:
  - platform: i2s_audio
    name: "SpeakerA"
    dac_type: external
    i2s_dout_pin: GPIO12   # Data Output pin
    on_announcement:
      then:
      - output.turn_on: PAM8302_mute
    on_play:
      then:
      - output.turn_on: PAM8302_mute
    on_idle:
      then:
      - output.turn_off: PAM8302_mute


# TODO add LEDs

