esphome:
  name: speaker_a
  on_boot:
    priority: -100
    then:
      - media_player.volume_set:
          id: media_speaker_a
          volume: 1.0

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    #platform_version: https://github.com/swoboda1337/platform-espressif32.git#54_03_21_3

wifi:
  networks:
    - ssid: !secret wifi_name_soffitta
      password: !secret wifi_pw_soffitta
  power_save_mode: none

captive_portal:

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: ""
  platform: esphome

output:
  - platform: gpio
    pin: GPIO27
    id: PAM8302_mute

i2s_audio:
  - id: i2s_output
    i2s_lrclk_pin: GPIO14
    i2s_bclk_pin: GPIO13

speaker:
  - platform: i2s_audio
    id: speaker_a_output
    i2s_audio_id: i2s_output
    dac_type: external
    i2s_dout_pin: GPIO12
    sample_rate: 16000
    channel: mono

media_player:
  - platform: speaker
    name: "SpeakerA"
    id: media_speaker_a

    buffer_size: 40000

    announcement_pipeline:
      speaker: speaker_a_output
      format: WAV
      sample_rate: 16000
      num_channels: 1

    on_announcement:
      - output.turn_on: PAM8302_mute

    on_play:
      - output.turn_on: PAM8302_mute

    on_idle:
      - output.turn_off: PAM8302_mute


# TODO add LEDs
