esphome:
  name: speaker_a
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "SoffittaAXSlow"
  password: !secret wifi_pw_soffitta

  manual_ip:
    static_ip: 192.168.1.95
    gateway: 192.168.1.1
    subnet: 255.255.255.0

captive_portal:

logger:

api:
  password: ""

ota:
  password: ""
  platform: esphome

i2s_audio:
  i2s_lrclk_pin: GPIO12  # WS/LRCK pin
  i2s_bclk_pin: GPIO14   # Bit Clock pin

# Media Player setup
media_player:
  - platform: i2s_audio
    name: "SpeakerA"
    dac_type: external
    i2s_dout_pin: GPIO13   # Data Output pin

# TODO add output pin that deactivates amplifier
# TODO add buzzer and LEDs

