
esphome:
  name: stufa-control

esp32:
  board: esp32cam

logger:

api:
  password: ""

ota:
  password: ""
  platform: esphome

wifi:
  ssid: !secret wifi_name_soffitta
  password: !secret wifi_pw_soffitta

  # manual_ip:
  #   static_ip: 192.168.1.91
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0
  
# Camera
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]

  # The order of the data_pins is significant, don't mix up the order
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 320x240
  name: stufa-cam
  idle_framerate: 0.1fps
  max_framerate: 2fps

# Exposing virtual buttons to home assistant
button:
  - platform: template
    name: Stufa Fiamma
    id: pulsanteFiamma
    on_press:
      - switch.turn_on: relayFiamma
  - platform: template
    name: Stufa Ventola
    id: pulsanteVentola
    on_press:
      - switch.turn_on: relayVentola

# Connecting relay board
switch:
  - platform: gpio
    pin: GPIO4
    inverted: true
    id: relayFiamma
    name: "Stufa Fiamma"
    internal: true
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: relayFiamma
  - platform: gpio
    pin: GPIO13
    inverted: true
    id: relayVentola
    name: "Stufa Ventola"
    internal: true
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relayVentola