esphome:
  name: power-display

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "SoffittaAXSlow"
  password: "BelinoInverso"

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.99
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0


    
sensor:
  - platform: homeassistant
    entity_id: sensor.shellem_contatori_power_tot
    id: tot_power 
    

spi:
  clk_pin: GPIO6
  mosi_pin: GPIO8


display:
  - platform: max7219
    cs_pin: GPIO11
    num_chips: 1
    lambda: |-
      it.print("01234567");


     