esphome:
  name: water-level-pompe

esp8266:
  board: nodemcuv2

logger:

api:
  password: ""

ota:
  password: ""
  platform: esphome

wifi:
  ssid: !secret wifi_name_soffitta
  password: !secret wifi_pw_soffitta

uart:
  tx_pin: GPIO14 # D5
  rx_pin: GPIO12 # D6
  baud_rate: 9600

sensor:
  - platform: "jsn_sr04t"
    name: "Livello Intercapedine"
    id: livello_intercapedine
    filters:
      - quantile:
          window_size: 10
          send_every: 50
          send_first_at: 1
          quantile: .9

display:
  platform: tm1637
  id: tm1637_display
  clk_pin: D1
  dio_pin: D2
  # inverted: true
  length: 4
  lambda: |-
    it.printf("%4.0f", id(livello_intercapedine).state * 100);