esphome:
  name: water-level-pompe

esp8266:
  board: nodemcuv2

logger:

api:
  password: ""

ota:
  password: ""
  platform: esphome

wifi:
  ssid: !secret wifi_name_soffitta
  password: !secret wifi_pw_soffitta

uart:
  tx_pin: GPIO14 # D5
  rx_pin: GPIO12 # D6
  baud_rate: 9600

sensor:
  - platform: "jsn_sr04t"
    name: "Livello Intercapedine"
    id: livello_intercapedine
    update_interval: 1s
    filters:
      - clamp:
          min_value: 0.4
          max_value: 3.0
          ignore_out_of_range: true
      - sliding_window_moving_average:
          window_size: 7
          send_every: 3 # TODO slow down to 10sec
          send_first_at: 3
          # quantile: .9

display:
  platform: tm1637
  id: tm1637_display
  clk_pin: D1
  dio_pin: D2
  # inverted: true
  length: 4
  lambda: |-
    it.printf("%4.0f", id(livello_intercapedine).state * 100);